enabled = "yes"

[settings]
url_prefix = "/default_admin_alpinejs_example"
template_folder = "templates"
static_folder = "static"
#static_url_path = "/default_admin_alpinejs_example/static"

[session]
default_admin_alpinejs_example_session = "yes"

