enabled = "yes"

[settings]
url_prefix = "/fragment_alpinejs_example"
template_folder = "templates"
static_folder = "static"
#static_url_path = "/fragment_alpinejs_example/static"

[session]
fragment_alpinejs_example = "yes"

